name: watchpod
description: "A podcast aggregator for smartwatches - RSS feed based"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  xml: ^6.5.0
  just_audio: ^0.9.43
  path_provider: ^2.1.5
  dio: ^5.7.0
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
